---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.1.0.0

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  - sudo apt-get update -qq

install:
  # Install ansible and linter
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install --no-binary ansible ansible; else pip install --no-binary ansible ansible==$ANSIBLE_VERSION; fi
  - pip install ansible-lint==3.2.5

  # Check versions
  - ansible --version
  - ansible-lint --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Ansible lint
  - ansible-lint tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
