FROM ubuntu:14.04

RUN apt-get update -qq && apt-get install -qqy python

RUN apt-get update -qq && apt-get install -qqy python3 mpg123 faad vorbis-tools \
	flac imagemagick lame python3-unidecode git
