---
# tasks file for cherrymusic
- name: "install packages"
  apt:
    name:
      - python3
      - mpg123
      - faad
      - vorbis-tools
      - flac
      - imagemagick
      - lame
      - python3-unidecode
      - git
    state: present
    cache_valid_time: 28800  # 8h
    # Optionally, you can replace the packages "mpg123", "faad", "vorbis-tools",
    # "flac" and "lame" with "ffmpeg" if you like. The advantage with ffmpeg is
    # that you can also decode WMA files.

- name: "adduser"
  user: name="{{ cherrymusic_user }}"
    home="/home/{{ cherrymusic_user }}"
    createhome=yes
    state=present
    system=no

- name: "git clone"
  git:
    repo=git://github.com/devsnd/cherrymusic.git
    dest="/home/{{ cherrymusic_user }}/code/"
    version=devel
    accept_hostkey=yes
    update=yes
  become: true
  become_user: "{{ cherrymusic_user }}"

- name: "copy our cherrypy bootstrap script"
  copy: src=bootstrap.py
    dest="/home/{{ cherrymusic_user }}/code/bootstrap.py"
    owner=cherrymusic
    mode=0755

- name: "bootstrap cherrypy"
  shell: |
    set -o pipefail
    echo "y" | python3 bootstrap.py
  args:
    chdir: "/home/{{ cherrymusic_user }}/code/"
    creates: "/home/{{ cherrymusic_user }}/code/cherrypy"
  become: true
  become_user: "{{ cherrymusic_user }}"

- name: "create config dir"
  file: name="/home/{{ cherrymusic_user }}/.config/cherrymusic/"
    state=directory
    owner="{{ cherrymusic_user }}"
    mode=0755

- name: "copy config"
  template: src=cherrymusic.conf
    dest="/home/{{ cherrymusic_user }}/.config/cherrymusic/cherrymusic.conf"
    owner="{{ cherrymusic_user }}"
    mode=0644

- name: "cherrypy update"
  command: python3 ./cherrymusic --update
  args:
    chdir: "/home/{{ cherrymusic_user }}/code/"
  when: cherrymusic_update
  become: true
  become_user: "{{ cherrymusic_user }}"
